logger:
    file: /home/volte/repos/open5gs/install/var/log/open5gs/smf.log

smf:
    #sbi:
    #  - addr: 127.0.0.4
    #    port: 7777
    pfcp:
      - addr: 127.0.0.4
      - addr: ::1
    gtpc:
      - addr: 127.0.0.4
      - addr: ::1
    gtpu:
      - addr: 127.0.0.4
      - addr: ::1
    metrics:
      - addr: 127.0.0.4
        port: 9090
    subnet:
      - addr: 192.168.100.1/24
        apn: internet
      - addr: fd84:6aea:c36e:2b69::/48
        apn: internet
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
    mtu: 1400
    ctf:
      enabled: auto
    freeDiameter: /home/volte/repos/open5gs/install/etc/freeDiameter/smf.conf

scp:
    sbi:
      - addr: 127.0.1.10
        port: 7777


upf:
    pfcp:
      - addr: 127.0.0.7



parameter:


max:


time:
